version: '3.8'

services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      args:
        JAR_FILE: target/EverGrowFinance-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
    depends_on:
      - db

  frontend:
    build: ./evergrow-bank-ui
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db-data:
